app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# routes in site
homepage:
    path:      /
    defaults:  { _controller: AppBundle:Page:index }

registration:
    path:     /registration
    defaults: { _controller: AppBundle:Page:registration }
